# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rustIRL_Alarm.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pyautogui import *
import pyautogui
import time
import random
import keyboard
import os
import time

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(450, 90, 341, 451))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.scrollArea.setFont(font)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Box)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 339, 449))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(450, 10, 341, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 311, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 180, 311, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(330, 90, 111, 71))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(330, 170, 111, 71))
        self.pushButton_2.setObjectName("pushButton_2")
        self.yValueLabel = QtWidgets.QLabel(self.centralwidget)
        self.yValueLabel.setGeometry(QtCore.QRect(10, 210, 311, 21))
        self.yValueLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.yValueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.yValueLabel.setObjectName("yValueLabel")
        self.xValueLabel = QtWidgets.QLabel(self.centralwidget)
        self.xValueLabel.setGeometry(QtCore.QRect(10, 130, 311, 20))
        self.xValueLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.xValueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.xValueLabel.setObjectName("xValueLabel")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(10, 10, 211, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.startButton.setFont(font)
        self.startButton.setObjectName("startButton")
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setGeometry(QtCore.QRect(230, 10, 211, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.stopButton.setFont(font)
        self.stopButton.setObjectName("stopButton")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 540, 91, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 250, 431, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 280, 431, 261))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setFrameShape(QtWidgets.QFrame.Box)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # Where you add your button functionality
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "rustIRL_Alarm"))
        self.label.setText(_translate("MainWindow", "Console Log"))
        self.label_2.setText(_translate("MainWindow", "X Cordinate"))
        self.label_3.setText(_translate("MainWindow", "Y Cordinate"))
        self.pushButton.setText(_translate("MainWindow", "Set X Value"))
        self.pushButton_2.setText(_translate("MainWindow", "Set Y Value"))
        self.yValueLabel.setText(_translate("MainWindow", "yValueLabel"))
        self.xValueLabel.setText(_translate("MainWindow", "xValueLabel"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.label_4.setText(_translate("MainWindow", "Made by foenem"))
        self.label_5.setText(_translate("MainWindow", "Code Red Status"))
        self.label_6.setText(_translate("MainWindow", "False"))

        # START OF CODE
        # Implement functionality in functions
        start = False
        codeRed = False

        # Test function
        def clicked():
            print("Clicked")

        def startCheck():
            start = True
            print("Start is " + str(start))
            while keyboard.is_pressed('q') == False:
                
                if start == False:
                    print("Breaking")
                    break

                # Checks if Triggered
                # Note for later, the first two numbers are the x and y cords. You can find those by following the yt guide. He opens shell runs a couple commands and boom.
                # The 0 stands for Red, the three RGB values, 1 for green, 2 for blue
                # The == 109 is the first value of the triggered red rust+ alarm

                elif pyautogui.pixel(958, 388) [0] == 109:
                    print("Triggered")
                    codeRed = True
                    os.startfile('E:\\Everything\\Code Folder\\rustAlarm.mp4')
                    # Stops the program from freezing
                    start = False
        
                    # Checks if not triggered
                elif pyautogui.pixel(958, 388) [0] == 18:
                    print("Not Triggered")
                
                else:
                    print("Nothing detected, not triggered or triggered")
                    


        def stopCheck():
            start = False
            print("Start is " + str(start))

        

        self.startButton.clicked.connect(startCheck)
        self.stopButton.clicked.connect(stopCheck)

        
            


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
